#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 获取所有已暂存的文件
STAGED_FILES=$(git diff --cached --name-only)

# 定义要检查的文件扩展名
FILE_EXTENSIONS=("html" "vue" "ts" "js" "json" "md")

# 对已暂存的文件运行 Prettier
for FILE in $STAGED_FILES; do
  # 获取文件的扩展名
  EXT="${FILE##*.}"
  echo "${EXT}"

  # 检查文件扩展名是否在列表中
  if [[ " ${FILE_EXTENSIONS[@]} " =~ " ${EXT} " ]]; then
    # 检查文件是否需要格式化
    if ! npx prettier --check "$FILE"; then
      echo "Formatting $FILE..."
      npx prettier --write "$FILE"
      # 如果文件被 Prettier 修改，则添加到暂存区
      git add "$FILE"
    fi
  fi
done

